"""
Ablation A1, step 2: re-attach the test oracles and measure.

Given a folder with the solutions generated by generator.py in ablation mode
(test methods marked with the {:verify false} attribute, so that their assertions
did NOT take part in the acceptance criterion), this script:

  1. selects, for each program, the accepted solution (the last attempt, which is
     the one on which the generation loop stopped) and confirms that it verifies;
  2. removes the {:verify false} attributes, so that the original test assertions
     are checked again against the generated specification;
  3. verifies the result and classifies the outcome.

Outcomes per program:
  ORACLE_PASS      the generated specification satisfies the test assertions.
                   Conclusive: the specification is strong enough.
  ORACLE_FAIL      the test assertions do not verify. Ambiguous: either the
                   specification is too weak or incorrect, or it is adequate but
                   the verifier needs proof helpers in the test code that were
                   not generated. Resolved by the restricted repair phase (step 3)
                   and, for what remains, by manual classification (step 5).
  NOT_ACCEPTED     no attempt was accepted in the generation phase.
  VACUOUS_SUSPECT  as ORACLE_PASS or ORACLE_FAIL, but the generated contract
                   contains a literally unsatisfiable precondition, which makes
                   verification trivial. Reported separately.

Usage:
    python ablation_reattach.py <folder_with_generated_solutions> [--out results.csv]
    python ablation_reattach.py --control            # sanity check on expert solutions

Configuration (DAFNY_EXECUTABLE, verifier timeout) is read from .env, as in
generator.py.
"""

import argparse
import csv
import os
import re
import subprocess
import sys
import tempfile
from collections import defaultdict
from pathlib import Path

# ---------------------------------------------------------------- configuration

def _clean_value(v):
    """Strip surrounding quotes and a Python-style r/R prefix, if present."""
    v = v.strip()
    if v[:1] in ("r", "R") and v[1:2] in (chr(34), chr(39)):
        v = v[1:]
    if len(v) >= 2 and v[0] == v[-1] and v[0] in (chr(34), chr(39)):
        v = v[1:-1]
    return v


def _load_env(path=Path(__file__).with_name(".env")):
    if path.exists():
        for line in path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                k, v = line.split("=", 1)
                os.environ.setdefault(k.strip(), _clean_value(v))


_load_env()

DAFNY = os.environ.get("DAFNY_EXECUTABLE")
if not DAFNY:
    raise SystemExit("Missing configuration: set DAFNY_EXECUTABLE in python_scripts/.env")

VERIFIER_TIMEOUT = int(os.environ.get("TESTDAFNY_VERIFIER_TIMEOUT", "60"))

# ---------------------------------------------------------------- Dafny helpers

# {:verify false} attribute, as inserted by generator.disable_test_method_verification
VERIFY_FALSE = re.compile(r"\{\s*:verify\s+false\s*\}\s*")

# a literally unsatisfiable precondition
VACUOUS_PRECONDITION = re.compile(r"^\s*requires\s+false\s*(;|$)", re.MULTILINE)

SUMMARY = re.compile(r"Dafny program verifier finished with (\d+) verified, (\d+) error[s]?"
                     r"(?:, (\d+) time out)?(?:s)?(?:, (\d+) inconclusive)?")


def remove_verify_false(text):
    """Remove the {:verify false} attributes, re-enabling the test oracles."""
    return VERIFY_FALSE.sub("", text)


def verify(path):
    """Run 'dafny verify' on a file. Returns (ok, n_verified, n_errors, output)."""
    try:
        proc = subprocess.run(
            [DAFNY, "verify", str(path),
             "--verification-time-limit:" + str(VERIFIER_TIMEOUT),
             "--allow-warnings:true"],
            capture_output=True, timeout=VERIFIER_TIMEOUT * 10)
    except subprocess.TimeoutExpired:
        return False, 0, -1, "TIMEOUT"
    out = proc.stdout.decode("utf-8", errors="replace")
    m = SUMMARY.search(out)
    if m:
        verified = int(m.group(1))
        errors = int(m.group(2))
        timeouts = int(m.group(3) or 0)
        inconclusive = int(m.group(4) or 0)
        # a verification task that times out or is inconclusive is NOT a success,
        # even though Dafny reports it separately from the error count
        ok = errors == 0 and timeouts == 0 and inconclusive == 0
        return ok, verified, errors + timeouts + inconclusive, out
    return False, 0, -1, out


def verify_text(text, name):
    """Verify Dafny source held in a string, via a temporary file."""
    tmpdir = tempfile.mkdtemp(prefix="reattach_")
    path = os.path.join(tmpdir, name)
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)
    try:
        return verify(path)
    finally:
        try:
            os.remove(path)
            os.rmdir(tmpdir)
        except OSError:
            pass


# ---------------------------------------------------------------- run inspection

# generator.py names its outputs <Program>_<attempt>_llm.dfy
ATTEMPT = re.compile(r"^(?P<program>.+)_(?P<attempt>\d+)_llm\.dfy$")


def last_attempt_per_program(folder):
    """Map each program to its highest-numbered attempt file (the one the loop
    stopped on, i.e. the accepted solution when the program was solved)."""
    best = {}
    for entry in os.listdir(folder):
        m = ATTEMPT.match(entry)
        if m:
            program, attempt = m.group("program"), int(m.group("attempt"))
            if program not in best or attempt > best[program][0]:
                best[program] = (attempt, os.path.join(folder, entry))
    return best


# ---------------------------------------------------------------------- analysis

def reattach(program, folder, text):
    """Restore the test oracles in a generated solution.

    Ablation A1: the test methods are present but marked {:verify false}; the
    attribute is removed. Ablation A2: the test methods were removed altogether
    and saved by generator.py to <Program>_tests.dfy; that file is appended back.
    The saved methods are the stripped ones, i.e. exactly the test code the
    baseline pipeline receives, without the "// helper" assertions.
    """
    sidecar = os.path.join(folder, program + "_tests.dfy")
    if os.path.exists(sidecar):
        tests = Path(sidecar).read_text(encoding="utf-8", errors="replace")
        return text.rstrip() + chr(10) + chr(10) + tests, "A2"
    return remove_verify_false(text), "A1"


def analyse_solution(program, path):
    """Verify a generated solution with and without the test oracles."""
    folder = os.path.dirname(path)
    text = Path(path).read_text(encoding="utf-8", errors="replace")
    had_attribute = VERIFY_FALSE.search(text) is not None

    accepted, _, _, _ = verify(path)
    if not accepted:
        return dict(program=program, file=os.path.basename(path),
                    oracles_disabled=had_attribute, accepted=False,
                    outcome="NOT_ACCEPTED", errors_with_oracle="",
                    vacuous_precondition=bool(VACUOUS_PRECONDITION.search(text)),
                    reattached_file="")

    reattached, mode = reattach(program, folder, text)

    # keep the re-attached program, so that the restricted repair phase operates
    # on exactly the artefact measured here
    out_dir = os.path.join(folder, "_reattached")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, program + "_reattached.dfy")
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        f.write(reattached)

    ok, _, errors, _ = verify(out_path)
    vacuous = bool(VACUOUS_PRECONDITION.search(reattached))
    outcome = "ORACLE_PASS" if ok else "ORACLE_FAIL"
    if vacuous:
        outcome = "VACUOUS_SUSPECT/" + outcome
    return dict(program=program, file=os.path.basename(path),
                oracles_disabled=(mode == "A1" and had_attribute) or mode == "A2",
                accepted=True, outcome=outcome, errors_with_oracle=errors,
                vacuous_precondition=vacuous,
                reattached_file=os.path.relpath(out_path, folder))


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("folder", nargs="?", help="folder with generated solutions")
    ap.add_argument("--out", default=None, help="CSV file to write (default: <folder>/_reattach.csv)")
    ap.add_argument("--control", action="store_true",
                    help="sanity check: verify the expert programs of the dataset instead")
    args = ap.parse_args()

    if args.control:
        folder = os.environ.get("TESTDAFNY_INPUT_FOLDER")
        if not folder:
            raise SystemExit("Set TESTDAFNY_INPUT_FOLDER in .env to use --control")
        files = sorted(f for f in os.listdir(folder) if f.endswith(".dfy"))
        print(f"Control: verifying {len(files)} expert programs in {folder}")
        failed = []
        for i, name in enumerate(files, 1):
            ok, _, errors, _ = verify(os.path.join(folder, name))
            if not ok:
                failed.append((name, errors))
            print(f"  [{i:3}/{len(files)}] {name:45} {'ok' if ok else 'FAILED (%s errors)' % errors}")
        print(f"\nControl result: {len(files) - len(failed)}/{len(files)} verify with oracles enabled")
        if failed:
            print("Failures:", failed)
        return

    if not args.folder:
        ap.error("a folder with generated solutions is required (or use --control)")

    best = last_attempt_per_program(args.folder)
    if not best:
        raise SystemExit(f"No files matching <Program>_<attempt>_llm.dfy found in {args.folder}")

    rows = []
    counts = defaultdict(int)
    print(f"Analysing {len(best)} programs in {args.folder}\n")
    for i, (program, (attempt, path)) in enumerate(sorted(best.items()), 1):
        row = analyse_solution(program, path)
        row["attempts"] = attempt
        rows.append(row)
        counts[row["outcome"]] += 1
        print(f"  [{i:3}/{len(best)}] {program:40} attempts={attempt:<3} {row['outcome']}")

    out = args.out or os.path.join(args.folder, "_reattach.csv")
    with open(out, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["program", "file", "attempts", "oracles_disabled",
                                          "accepted", "outcome", "errors_with_oracle",
                                          "vacuous_precondition", "reattached_file"])
        w.writeheader()
        w.writerows(rows)

    total = len(rows)
    accepted = sum(1 for r in rows if r["accepted"])
    print("\n" + "=" * 62)
    print(f"Programs analysed              : {total}")
    print(f"Accepted in generation phase   : {accepted}")
    for outcome, n in sorted(counts.items()):
        share = 100.0 * n / total if total else 0.0
        print(f"  {outcome:28} : {n:3}  ({share:.1f}%)")
    print("=" * 62)
    print(f"\nPer-program results written to {out}")
    fails = [r["program"] for r in rows if r["outcome"].endswith("ORACLE_FAIL")]
    if fails:
        print(f"\n{len(fails)} program(s) for the restricted repair phase (step 3):")
        print("  " + ", ".join(fails))


if __name__ == "__main__":
    main()
